### ISSUE TITLE
Document usage with TypeScript's strict mode

### ISSUE THREAD

**Issue by GregOnNet** [typebytes/ngx-template-streams#6]
# 🚀 Documentation request

### Description

🙏 Thank you for building this awesome library!
It makes it even easier to work with Streams inside the component.

For now, using the Decorator `@ObservableEvent()` does not work out-of-the box if TypeScript has some strict options enabled.

To help developers using/activating the stricter TypeScript it would help to add a few notes how the syntax changes. 

### Describe the solution you'd like
If you consider a docs section you can add a paragraph.

#### Dealing with TypeScript's strict compiler options

If you are working with TypeScript's `strict mode` or have set `strictPropertyInitialization` to `true` in your `tsconfig.json`, you will experience an error using `@ObservableEvent()`.

```ts
@ObservableEvent()
click$: Observable<MouseEvent>;
//   ^ Property 'click$' has no initializer 
//     and is not definitely assigned in the constructor.
```

You can easily get around this using the `non-null-assertion` operator of TypeScript.

```diff
@ObservableEvent()
- click$: Observable<MouseEvent>;
+ click$!: Observable<MouseEvent>; 
```

**Additional context**
🙇‍♂️ Sorry, for disturbing your presentation during Angular Air episode.
It was not my intention to break your flow.

**Comment by d3lm** [comment]
Hey @GregOnNet, thank you for this detailed documentation request! Do you want to work on a PR maybe?

I would suggest to add this to the FAQ section.

**Comment by d3lm** [comment]
Hey @GregOnNet, any updates on this? Do you still want to contribute to the docs and add a small section on this to the readme?

**Comment by GregOnNet** [comment]
Hi 🤗,

I will take care of it this weekend.

Cheers!

**Comment by d3lm** [comment]
Nice! Thanks Gregor 👍

**Comment by d3lm** [comment]
I suppose this can be closed because the corresponding PR was merged already.
