### ISSUE TITLE
Doesn't work after navigating back and forth between routes.

### ISSUE THREAD

**Issue by fxck** [typebytes/ngx-template-streams#7]
## 🔬 Minimal Reproduction
https://github.com/fxck/ngx-template-streams-destroy-bug

- npm start
- click the button (works)
- click the link to go to the second page
- click the link to go back to the first page
- click the button (doesn't work)

![](https://media.giphy.com/media/Sx9Q4EYirJnN4hN2Ii/giphy.gif)

@d3lm

**Comment by d3lm** [comment]
Thanks for this issue! I am aware of this and will fix it ASAP. I already have it implemented and only need to push the changes and publish a new version.

Also, thanks for using this lib and providing feedback! Really appreciate it. How is it going so far?

**Comment by fxck** [comment]
Slowly implementing it. Seems to be working fine except for this and the other thing. 👍

**Comment by fxck** [comment]
Any chance you could push that fix @d3lm?

**Comment by d3lm** [comment]
Yep, will do that tonight.

**Comment by fxck** [comment]
👋

**Comment by d3lm** [comment]
I haven't forgotten about this. I am working on those two new decorators and I ll cut a new release once they are done. That release will also contain the fix. Sorry for the delay, I am doing my best to get this done.

**Comment by fxck** [comment]
Thank you!

**Comment by d3lm** [comment]
Should be fixed with [this](https://github.com/typebytes/ngx-template-streams/commit/bbc9b8e1e490ffb9ced5a9e64b200ae14f12beab) commit. This is published to npm as well, so make sure to grab v1.2.0.

Can you please give it a try and let me know? Also see the two new decorators `ObservableChild` and `ObservableChildren`.

**Comment by fxck** [comment]
Seems to be working fine. 👍

**Comment by d3lm** [comment]
Thanks for checking!
