### ISSUE TITLE
ngx-template-streams (ObservableEvent) and Observable ViewModel uses the same techniques (ObsFromEvent)

### ISSUE THREAD

**Issue by HansS** [typebytes/ngx-template-streams#9]
### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 Step-by-step instructions to reproduce the problem...

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

**Angular:**

<pre><code>

</code></pre>

**ngx-template-streams:**

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by d3lm** [comment]
Hey there! Could you please fill in all the information asked for in the issue template? I don't know what the issue is and how to reproduce it.

**Comment by d3lm** [comment]
Closing due to no clear description and inactivity.
